server:
  port: ${PORT:8084}

spring:
  application:
    name: notification-service

  rabbitmq:
    uri: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672/}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${MAIL_FROM}

rabbit:
  exchange: healthcare.exchange
  queue: appointment.queue
  routing-key: healthcare.routingkey


logging:
  level:
    com.healthcare.notification: DEBUG