ALTER TABLE patients
ALTER COLUMN email DROP NOT NULL,
ALTER COLUMN date_of_birth DROP NOT NULL,
ALTER COLUMN gender DROP NOT NULL;

ALTER TABLE patients ADD COLUMN is_profile_completed BOOLEAN NOT NULL DEFAULT FALSE;
