server:
  port: 8089

spring:
  application:
    name: receipt-service
  datasource:
    url: jdbc:postgresql://localhost:5432/receipt_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
