-- V1__create_prescription_tables.sql

CREATE TABLE prescription (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_id BIGINT NOT NULL,
    patient_name VARCHAR(255) NOT NULL,
    doctor_id BIGINT NOT NULL,
    doctor_name VARCHAR(255) NOT NULL,
    instruction TEXT NOT NULL,
    visit_date DATE NOT NULL,
    symptoms TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE medicine_summary (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prescription_id BIGINT NOT NULL REFERENCES prescription(id) ON DELETE CASCADE,
    drug_name VARCHAR(255) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    frequency VARCHAR(50) NOT NULL,
    duration_days INT NOT NULL,
    route VARCHAR(50) NOT NULL,
    instructions TEXT
);
