DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'pharmacist'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE public.pharmacist
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
DECLARE
    seq_name TEXT;
    next_id BIGINT;
BEGIN
    SELECT pg_get_serial_sequence('public.pharmacist', 'id')
    INTO seq_name;

    IF seq_name IS NULL THEN
        RAISE EXCEPTION 'No sequence attached to public.pharmacist.id';
    END IF;

    SELECT COALESCE(MAX(id), 0) + 1
    INTO next_id
    FROM public.pharmacist;

    EXECUTE format('SELECT setval(%L, %s, false)', seq_name, next_id);
END $$;

